import { useEffect, useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Editor from '@monaco-editor/react';
import { ChevronLeft, ChevronRight, ChevronUp } from 'lucide-react';
import { useEditorStore } from '@/store/editorStore';
import { Button } from '@/components/ui/button';
import TopBar from '@/components/editor/TopBar';
import Sidebar from '@/components/editor/Sidebar';
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@/components/ui/resizable';
import AIChat from '@/components/editor/AIChat';
import Terminal from '@/components/editor/Terminal';
import * as Y from 'yjs';
import { WebsocketProvider } from 'y-websocket';
import { MonacoBinding } from 'y-monaco';
import { useParams } from 'react-router-dom';

const EditorPage = () => {
  const { projectId } = useParams();
  const {
    currentFile,
    files,
    updateFileContent,
    terminalOpen,
    toggleTerminal,
    leftSidebarOpen,
    rightSidebarOpen,
    toggleLeftSidebar,
    toggleRightSidebar,
    role,
  } = useEditorStore();

  const [onlineUsers, setOnlineUsers] = useState(1);
  const [isDocReady, setIsDocReady] = useState(false);
  const providerRef = useRef<WebsocketProvider | null>(null);
  const bindingRef = useRef<any>(null);
  const docRef = useRef<Y.Doc | null>(null);

  useEffect(() => {
    return () => {
      // Clean up WebSocket connection and CRDT listeners on unmount
      bindingRef.current?.destroy();
      providerRef.current?.disconnect();
      docRef.current?.destroy();
    };
  }, []);

  const handleEditorMount = (editor: any, monaco: any) => {
    const doc = new Y.Doc();
    docRef.current = doc;
    setIsDocReady(true);

    const roomName = `codecolab-room-${projectId || 'demo'}`;
    // Using demo Yjs signaling server for real-time WebSockets
    const provider = new WebsocketProvider('wss://demos.yjs.dev/ws', roomName, doc);
    providerRef.current = provider;

    const colors = ['#f87171', '#fb923c', '#fbbf24', '#a3e635', '#4ade80', '#34d399', '#2dd4bf'];
    const myColor = colors[Math.floor(Math.random() * colors.length)];
    const myName = `Anon ${Math.floor(Math.random() * 100)}`;
    
    // Yjs injects the color directly via style tag, but we also attach it via CSS var for our custom labels
    provider.awareness.setLocalStateField('user', {
      name: myName,
      color: myColor
    });

    const type = doc.getText('monaco');
    const binding = new MonacoBinding(type, editor.getModel(), new Set([editor]), provider.awareness);
    bindingRef.current = binding;

    provider.awareness.on('change', () => {
      const states = Array.from(provider.awareness.getStates().values());
      // @ts-ignore
      const users = states.map(s => s.user).filter(Boolean);
      useEditorStore.getState().setOnlineUsers(users);
      setOnlineUsers(provider.awareness.getStates().size);

      // Inject the names into the DOM elements generated by y-monaco
      setTimeout(() => {
        const cursorHeads = document.querySelectorAll('.yRemoteSelectionHead');
        cursorHeads.forEach((head) => {
          // The color is applied inline to the style by y-monaco
          const color = (head as HTMLElement).style.borderColor;
          (head as HTMLElement).style.setProperty('--yjs-color', color);
          
          // Match the color to the user's name to display it dynamically
          const matchedUser = users.find(u => CSS.supports('color', u.color) || u.color === color);
          if (matchedUser) {
            head.setAttribute('data-client-name', matchedUser.name);
          } else {
             head.setAttribute('data-client-name', 'Collaborator');
          }
        });
      }, 100);
    });
  };

  const currentFileName = files.find((f) => f.id === currentFile)?.name || 'Untitled';
  
  const getLanguageFromExtension = (filename: string) => {
    const ext = filename.split('.').pop()?.toLowerCase();
    switch (ext) {
      case 'ts': case 'tsx': return 'typescript';
      case 'js': case 'jsx': return 'javascript';
      case 'py': return 'python';
      case 'go': return 'go';
      case 'java': return 'java';
      case 'c': case 'cpp': case 'h': case 'hpp': return 'cpp';
      case 'cs': return 'csharp';
      case 'html': return 'html';
      case 'css': return 'css';
      case 'json': return 'json';
      case 'md': return 'markdown';
      case 'sql': return 'sql';
      case 'sh': case 'bash': return 'shell';
      default: return 'plaintext';
    }
  };
  const language = getLanguageFromExtension(currentFileName);

  return (
    <div className="h-screen flex flex-col bg-background">
      <TopBar />

      <ResizablePanelGroup direction="horizontal" className="flex-1 overflow-hidden">
        {/* Left Sidebar Toggle */}
        {!leftSidebarOpen && (
          <Button
            variant="ghost"
            size="icon"
            onClick={toggleLeftSidebar}
            className="absolute left-0 top-20 z-10 bg-surface border-r border-y border-border hover:bg-muted shadow-sm w-6 h-8 rounded-l-none"
          >
            <ChevronRight className="w-3 h-3" />
          </Button>
        )}

        {/* Left Sidebar */}
        {leftSidebarOpen && (
          <>
            <ResizablePanel defaultSize={20} minSize={10} maxSize={40} className="relative bg-surface flex flex-col">
              <Sidebar doc={docRef.current} />
            </ResizablePanel>
            <ResizableHandle className="w-1 bg-border hover:bg-primary/50 transition-colors" />
          </>
        )}

        {/* Editor */}
        <ResizablePanel defaultSize={60} minSize={30} className="flex flex-col">
          <div className="flex-1 overflow-hidden relative">
            <Editor
              height="100%"
              language={language}
              onMount={handleEditorMount}
              theme="vs-dark"
              options={{
                minimap: { enabled: true },
                fontSize: 14,
                fontFamily: 'JetBrains Mono, Fira Code, monospace',
                lineNumbers: 'on',
                renderWhitespace: 'selection',
                scrollBeyondLastLine: false,
                automaticLayout: true,
                readOnly: role === 'viewer',
              }}
            />
          </div>

          {/* Terminal */}
          {terminalOpen && (
            <div className="h-48 relative">
              <Terminal doc={docRef.current} />
              <Button
                variant="ghost"
                size="icon"
                onClick={toggleTerminal}
                className="absolute right-2 top-2 bg-surface border border-border hover:bg-muted"
              >
                <ChevronUp className="w-4 h-4" />
              </Button>
            </div>
          )}

          {!terminalOpen && (
            <div className="h-8 bg-card border-t border-border flex items-center justify-between px-4">
              <div className="flex items-center gap-4 text-xs text-muted-foreground">
                <button
                  onClick={toggleTerminal}
                  className="hover:text-foreground transition-colors"
                >
                  Terminal
                </button>
                <span className="flex items-center gap-1">
                  <span className="w-2 h-2 rounded-full bg-success"></span>
                  Connected
                </span>
                <span>👥 {onlineUsers} collaborator{onlineUsers !== 1 ? 's' : ''} online</span>
              </div>
              <div className="flex items-center gap-4 text-xs text-muted-foreground">
                <span>TypeScript</span>
                <span>Ln 15, Col 22</span>
              </div>
            </div>
          )}
        </ResizablePanel>

        {/* Right Sidebar Toggle */}
        {!rightSidebarOpen && (
          <Button
            variant="ghost"
            size="icon"
            onClick={toggleRightSidebar}
            className="absolute right-0 top-20 z-10 bg-surface border-l border-y border-border hover:bg-muted shadow-sm w-6 h-8 rounded-r-none"
          >
            <ChevronLeft className="w-3 h-3" />
          </Button>
        )}

        {/* Right Sidebar */}
        {rightSidebarOpen && (
          <>
            <ResizableHandle className="w-1 bg-border hover:bg-primary/50 transition-colors" />
            <ResizablePanel defaultSize={20} minSize={15} maxSize={40} className="relative bg-surface flex flex-col">
              <div className="w-full h-full">
                <AIChat doc={docRef.current} />
              </div>
            </ResizablePanel>
          </>
        )}
      </ResizablePanelGroup>
    </div>
  );
};

export default EditorPage;
